// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlapBott.Data;

#nullable disable

namespace SlapBott.Data.Migrations
{
    [DbContext(typeof(SlapbottDbContext))]
    [Migration("20240307001845_Adding CombatState")]
    partial class AddingCombatState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlapBott.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CharExp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasLeveled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ElementalType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatTypeRatio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SlapBott.Data.Models.SubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SubClass");
                });

            modelBuilder.Entity("SlapBott.Data.Models.TurnAttackRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TurnId");

                    b.ToTable("TurnAttackRecord");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.CombatState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CurrentTurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CombatStates");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackerId")
                        .HasColumnType("integer");

                    b.Property<int>("CombatStateId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTurnId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.HasIndex("TurnId", "CombatStateId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Character", b =>
                {
                    b.HasOne("SlapBott.Data.Models.SubClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("SlapBott.Data.Models.TurnAttackRecord", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.Turn", "Turn")
                        .WithMany("AttackRecords")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Character", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", "CombatState")
                        .WithMany("Turns")
                        .HasForeignKey("TurnId", "CombatStateId")
                        .HasPrincipalKey("CurrentTurnId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("CombatState");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.CombatState", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.Navigation("AttackRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
