// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlapBott.Data;

#nullable disable

namespace SlapBott.Data.Migrations
{
    [DbContext(typeof(SlapbottDbContext))]
    partial class SlapbottDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlapBott.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CharExp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("HasLeveled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("Character");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SlapBott.Data.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CharExp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("Enemies", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Enemy");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SlapBott.Data.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveCharacterId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCharacterId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SlapBott.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ElementalType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatTypeRatio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SlapBott.Data.Models.SubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SubClass");
                });

            modelBuilder.Entity("SlapBott.Data.Models.TurnAttackRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TurnId");

                    b.ToTable("TurnAttackRecord");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.CombatState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CurrentTurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CombatStates");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.EnemyCombatState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CombatStateId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CombatStateId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("EnemyCombatState");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.PlayerCharacterCombatState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CombatStateId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CombatStateId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("PlayerCharacterCombatState");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackerId")
                        .HasColumnType("integer");

                    b.Property<int>("CombatStateId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.HasIndex("TurnId", "CombatStateId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("SlapBott.Data.Models.PlayerCharacter", b =>
                {
                    b.HasBaseType("SlapBott.Data.Models.Character");

                    b.Property<int>("DiscordID")
                        .HasColumnType("integer");

                    b.HasIndex("DiscordID");

                    b.HasDiscriminator().HasValue("PlayerCharacter");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Boss", b =>
                {
                    b.HasBaseType("SlapBott.Data.Models.Enemy");

                    b.HasDiscriminator().HasValue("Boss");
                });

            modelBuilder.Entity("SlapBott.Data.Models.RaidBoss", b =>
                {
                    b.HasBaseType("SlapBott.Data.Models.Boss");

                    b.HasDiscriminator().HasValue("RaidBoss");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Character", b =>
                {
                    b.HasOne("SlapBott.Data.Models.SubClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Enemy", b =>
                {
                    b.HasOne("SlapBott.Data.Models.SubClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Registration", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("ActiveCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SlapBott.Data.Models.TurnAttackRecord", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.Turn", "Turn")
                        .WithMany("AttackRecords")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.EnemyCombatState", b =>
                {
                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", "CombatState")
                        .WithMany()
                        .HasForeignKey("CombatStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", null)
                        .WithMany("Enemies")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Data.Models.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatState");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.PlayerCharacterCombatState", b =>
                {
                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", "CombatState")
                        .WithMany()
                        .HasForeignKey("CombatStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", null)
                        .WithMany("Characters")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Data.Models.PlayerCharacter", "Character")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CombatState");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Character", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlapBott.Services.Combat.Models.CombatState", "CombatState")
                        .WithMany("Turns")
                        .HasForeignKey("TurnId", "CombatStateId")
                        .HasPrincipalKey("CurrentTurnId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("CombatState");
                });

            modelBuilder.Entity("SlapBott.Data.Models.PlayerCharacter", b =>
                {
                    b.HasOne("SlapBott.Data.Models.Registration", "Registration")
                        .WithMany("PlayerCharacters")
                        .HasForeignKey("DiscordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("SlapBott.Data.Models.Registration", b =>
                {
                    b.Navigation("PlayerCharacters");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.CombatState", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Enemies");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("SlapBott.Services.Combat.Models.Turn", b =>
                {
                    b.Navigation("AttackRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
